# Project for linear algebra

## Importing required packages

In [14]:
import numpy as np;

## Defining basic matrix

In [195]:
basic_matrix = np.array([[3, 2, 3, 1],
                         [4, 9, 6, 4],
                         [8, 7, 2, 5],
                         [8, 0, 2, 1]])

basic_matrix = np.array([[5, 6, 6, 8],
                         [4, 1, 1, 1],
                         [7, 0, 3, 0],
                         [1, 0, 8, 2]])

basic_matrix = np.array([[4, 6, 4, 1],
                         [8, 5, 0, 1],
                         [9, 7, 1, 0],
                         [2, 5, 5, 3]])

basic_matrix = np.array([[8, 8, 5, 0],
                         [8, 7, 8, 5],
                         [8, 4, 5, 0],
                         [4, 7, 5, 5]])

basic_matrix = np.array([[5, 4, 4, 0],
                         [5, 3, 5, 0],
                         [8, 2, 2, 8],
                         [6, 0, 9, 0]])

basic_matrix = np.array([[1, 1, 4, 2],
                         [7, 9, 7, 4],
                         [7, 6, 9, 4],
                         [2, 4, 6, 4]])

basic_matrix = np.array([[1, 1, 4, 2],
                         [7, 9, 7, 4],
                         [7, 6, 9, 4],
                         [1, 4, 6, 4]])

print(basic_matrix)

[[4 6 4 1]
 [8 5 0 1]
 [9 7 1 0]
 [2 5 5 3]]


In [122]:
basic_matrix = np.random.randint(10, size=(4, 4))
print(basic_matrix)

[[8 5 3 5]
 [3 4 9 0]
 [6 8 0 4]
 [8 9 5 1]]


In [484]:
basic_matrix = np.array([[1, 1, 1, 2],
                         [6, 8, 6, 2],
                         [7, 6, 9, 4],
                         [1, 4, 6, 4]])

matrix_det = np.linalg.det(basic_matrix)
print(matrix_det)

if matrix_det != 0:
    matrix_inv = np.linalg.inv(basic_matrix)
    print(matrix_inv)

218.00000000000017
[[ 0.22018349 -0.01834862  0.16513761 -0.26605505]
 [ 0.02752294  0.24770642 -0.2293578   0.09174312]
 [-0.4587156  -0.12844037  0.1559633   0.13761468]
 [ 0.60550459 -0.05045872 -0.04587156  0.01834862]]


In [480]:
def correctMatrix(mat):
    return np.issubdtype(mat.dtype, np.floating)

basic_matrix = np.array([[1, 1, 2, 2],
                         [2, 2, 6, 5],
                         [5, 5, 9, 9],
                         [1, 2, 7, 4]])

# print(correctMatrix(basic_matrix))

matrix_det = np.linalg.det(basic_matrix)
print(matrix_det)

if matrix_det != 0:
    matrix_inv = np.linalg.inv(basic_matrix)
    print(correctMatrix(matrix_inv))
    print(matrix_inv)

-0.9999999999999991
True
[[-1.90000000e+01  3.00000000e+00  3.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+01 -3.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [-7.00000000e+00  1.00000000e+00  1.00000000e+00 -2.77555756e-16]
 [ 1.20000000e+01 -1.00000000e+00 -2.00000000e+00  5.55111512e-16]]


In [477]:
def correctMatrix(mat):
    return not(np.issubdtype(mat.dtype, np.floating))

while True:
    basic_matrix = np.random.randint(10, size=(4, 4))
    
    matrix_det = np.linalg.det(basic_matrix)
    if matrix_det == 0:
        continue
    
    matrix_inv = np.linalg.inv(basic_matrix)
    if correctMatrix(matrix_inv) == True:
        break
        
print(basic_matrix)
matrix_det = np.linalg.det(basic_matrix)
print(matrix_det)

if matrix_det != 0:
    matrix_inv = np.linalg.inv(basic_matrix)
    print(matrix_inv)

KeyboardInterrupt: 